import easydict

cfg = easydict.EasyDict()


'''URL CLUSTER HYPERPARAMETERS'''
cfg.GLOBAL_N_JOBS = 8
# url vectorize params
cfg.ASCII_SIZE = 128
# k-means/hierarchical cluster params
cfg.N_CLUSTER_RATION = 2000
# distance metric
cfg.EDIT_DISTANCE_THRESH_LONG = 0.3
cfg.EDIT_DISTANCE_THRESH_SHORT = 0.2
cfg.LONG_URL_THRESH = 100
cfg.SHORT_URL_THRESH = 4
# regex extract params
#   control cluster size
cfg.SMALL_CLUSTER_SIZE = 2
cfg.BIG_CLUSTER_SIZE = 5
cfg.BIG_CLUSTER_SAMPLE_ROUND = 10
#   control regex size
cfg.MIN_SUBSTRING_SIZE = 12
cfg.SINGLE_REGEX_SIZE = 12
cfg.TOTAL_REGEX_SIZE = 12
cfg.SINGLE_REGEX_SIZE_RATIO = 0.2
cfg.TOTAL_REGEX_SIZE_RATIO = 0.3
# publish
cfg.PUBLISH_FP_THRESH = 0
cfg.PUBLISH_TP_THRESH = 1
cfg.PUBLISH_RATIO = 0.5
cfg.PUBLISH_RATIO_TP_THRESH = 10


"""DOMAIN CLUSTER HYPERPARAMETERS"""
cfg.DOMAIN_LEVEL_FREQUENCY_THRESH = 0.2
cfg.TOP_DOMAIN_LEVEL_COUNT_THRESH = 3

cfg.DOMAIN_CLUSTER_SIZE_THRESH = 2
cfg.RANDOM_LEVEL_SAMPLE_ROUND = 5
cfg.RANDOM_LEVEL_SAMPLE_UPBOUND = 50
cfg.RANDOM_LEVEL_SAMPLE_RATIO = 0.4

